### ISSUE TITLE
update homepage URL

### ISSUE THREAD

**Issue by g-v-egidy** [ColinIanKing/forkstat#2]
The official upstream URL for forkstat was `https://kernel.ubuntu.com/~cking/forkstat/` in the past. But it now just gives a 404 error.

Could you please either bring back the old homepage or change the URL in the project listing and the packages you maintain (for example for ubuntu) to something that works. Thanks.

**Comment by ColinIanKing** [comment]
The original URL is dead. I've updated it to https://github.com/ColinIanKing/forkstat

**Comment by g-v-egidy** [comment]
Thank you! 

(also for developing & maintaining forkstat in the first place, I regularly use it for debugging)
