### ISSUE TITLE
monitor all processes in a cgroup or process group/tree

### ISSUE THREAD

**Issue by inorton** [ColinIanKing/forkstat#3]
I've been looking at using forkstat to more deeply profile what is going on inside a docker container. I can find my container's pid cgroup easily enough and then post-process the forkstat output when my container is finished doing it's job.

But it would be really nice if I could ask forkstat to limit what it reports to a specific cgroup or children of a given pid/pgroup

Thanks :)

**Comment by ColinIanKing** [comment]
I've added -p option that allows one to filter by process group id, see commit: 688311dbe0b5de474e1a5896eb9764c48250b3d1
