### ISSUE TITLE
socket failed: errno=1 (Operation not permitted)

### ISSUE THREAD

**Issue by simonwibberley** [ColinIanKing/forkstat#5]
Hi there,

on 
CentOS Linux release 7.9.2009 (Core) 
forkstat, version 0.02.16

installed via snap, I get the following error when running as root:

 `socket failed: errno=1 (Operation not permitted)`
 
 Could you advise? 

Many thanks!

**Comment by ColinIanKing** [comment]
I suggest installing the snap using devmode, e.g.

sudo snap install forkstat --devmode
