### ISSUE TITLE
Empty argument causes the rest to be ignored

### ISSUE THREAD

**Issue by grawity** [ColinIanKing/forkstat#6]
Hi,

With all current versions, if a program's command line has a zero-length arg, the forkstat output line stops at that arg and discards everything beyond:

```
$ /bin/true One Two "" Three Four
```

Output:

```
Time     Event     PID Info   Duration Process
07:37:25 fork   538365 parent          bash
07:37:25 fork   538433 child           bash
07:37:25 exec   538433                 /bin/true One Two
07:37:25 exit   538433      0   0.002s /bin/true One Two
```

**Comment by ColinIanKing** [comment]
Thanks for spotting this bug. Fixed with commit 97253bc2f2ded594bee858a7d779005d2725588d
