### ISSUE TITLE
Request for help - init'ing netlink socket

### ISSUE THREAD

**Issue by jimnarey** [ColinIanKing/forkstat#8]
Hi,

This isn't an issue with forkstat: I hope that's OK -

I am trying to reproduce some of forkstat's functionality in Python. It's a simple application to catch when a particular executable is exec'd or exits. At first, my code appeared not to work. However, when I ran forkstat (and exited) to test my kernel had the required features my code suddenly began working. It continues to work until reboot, after which it doesn't until I run forkstat again.

I think I'm missing the functionality of your `netlink_listen` function but my attempt at reproducing it doesn't work:

```
import os
import struct

...

NETLINK_CONNECTOR = 11  # include/uapi/linux/netlink.h
CN_IDX_PROC = 1  # include/uapi/linux/connector.h
CN_VAL_PROC = 1
NLMSG_DONE = 3
PROC_CN_MCAST_LISTEN = 1

...

def netlink_listen(sock):
    # 'III' - 3 x unsigned int
    nlmsghdr_size = struct.calcsize('III')
    # 'II' - 2 x unsigned int
    cn_msg_size = struct.calcsize('II')

    nlmsghdr_data = struct.pack('III', nlmsghdr_size + cn_msg_size + struct.calcsize('I'), os.getpid(), NLMSG_DONE)
    cn_msg_data = struct.pack('II', CN_IDX_PROC, CN_VAL_PROC) + struct.pack('I', cn_msg_size)
    op_data = struct.pack('I', PROC_CN_MCAST_LISTEN)

    message = nlmsghdr_data + cn_msg_data + op_data

    sock.sendall(message)
```

Can you point me to any documentation on how to initialise the socket, once it's been created and bound (as follows, in case it helps)? -

```
sock = socket.socket(socket.AF_NETLINK, socket.SOCK_RAW, NETLINK_CONNECTOR)
sock.bind((0, CN_IDX_PROC))
```

Thank you,

Jim.

**EDIT:** I've confirmed that the forkstat `netlink_listen` function is what's causing my code to work. If I replace:

```
return writev(sock, iov, 3);
```

with:

```
return 0;
```

My code does not receive events (and nor does forkstat, unsurprisingly).

I got the data sent by ` writev(sock, iov, 3)` by adding the following to the end of `netlink_listen` and tried sending that (converted back to binary) in my Python code but it didn't cause events to be received. 

```
	for (int i = 0; i < sizeof(struct iovec); i++) {
  		printf("%02X ", ((unsigned char*)&iov)[i]);
	}
```

**Comment by ColinIanKing** [comment]
I'm using SOCK_DGRAM on the socket, whereas your core seems to be using SOCK_RAW. I suggest running strace on my code to see the exact system calls and the order they are being used and running strace on your code and comparing the difference as a starting point to debugging this issue.  Hope that helps.
